# Generated by Django 4.2.20 on 2025-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_ride_rideevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("rider", "Rider"), ("driver", "Driver")],
                max_length=22,
            ),
        ),
    ]
